# Generated by Django 3.2 on 2021-04-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthdaydata',
            old_name='birthday_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='birthdaydata',
            old_name='birthday_name',
            new_name='name',
        ),
    ]
