# Generated by Django 3.2 on 2021-05-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaydata',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
